# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-18 21:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='file',
            field=models.ImageField(blank=True, upload_to='sub_photo/%Y/%m/%d/'),
        ),
    ]
