# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-08-15 17:58
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('news', '0002_auto_20170815_1706'),
    ]

    operations = [
        migrations.RenameField(
            model_name='photo',
            old_name='pos',
            new_name='post',
        ),
        migrations.AddField(
            model_name='post',
            name='author',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='location',
            field=models.TextField(default=' ', verbose_name='위도/경도'),
            preserve_default=False,
        ),
    ]
