# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-08-14 22:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Postprivacy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('policy', models.CharField(max_length=15, verbose_name='정책')),
            ],
        ),
        migrations.AddField(
            model_name='post',
            name='privacy',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='news_posts', to='news.Postprivacy', verbose_name='Privacy related'),
            preserve_default=False,
        ),
    ]
