# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-15 17:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_auto_20170815_1706'),
    ]

    operations = [
        migrations.RenameField(
            model_name='photo',
            old_name='pos',
            new_name='post',
        ),
    ]
