# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-08-15 16:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_auto_20170814_2221'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='location',
            field=models.TextField(default=' ', verbose_name='위도/경도'),
            preserve_default=False,
        ),
    ]
