# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-16 21:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_block_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report_Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=20, verbose_name='유저명')),
                ('content', models.CharField(max_length=100, verbose_name='신고내용')),
                ('title', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='news.Post')),
            ],
        ),
    ]
