# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-16 22:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_report_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='block_user',
            name='block_man_id',
            field=models.CharField(default='', max_length=20, verbose_name='차단된 유저ID'),
            preserve_default=False,
        ),
    ]
