# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-08-17 00:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_block_user_block_man_id'),
        ('news', '0003_auto_20170816_2004'),
    ]

    operations = [
    ]
