# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-08-17 22:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_toru',
            field=models.BooleanField(default=False, verbose_name='여행여부'),
        ),
    ]
