# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-08-17 23:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_profile_is_toru'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='is_toru',
            new_name='is_tour',
        ),
    ]
